[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.pgclient]
cmds = ["apt-get update && apt-get install -y lsb-release gnupg wget && sh -c 'echo \"deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main\" > /etc/apt/sources.list.d/pgdg.list' && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && apt-get update && apt-get install -y postgresql-client-17"]
dependsOn = ["setup"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]
dependsOn = ["pgclient"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run serve"

[variables]
NODE_ENV = "production"
